import { Suspense } from 'react';
import ClipArtIndexClient from './ClipArtIndexClient';

export const metadata = {
  title: 'Clip Art — Isolated Visual Assets Generated by Esy | Esy',
  description:
    'Browse clip art generated through the Generate Clip Art Asset workflow. Each asset is rendered on gpt-image-2, post-processed for transparent backgrounds, and stored as a versioned Esy artifact.',
  keywords: [
    'clip art',
    'transparent clip art',
    'generated clip art',
    'cartoon clip art',
    'chibi clip art',
    'illustrated clip art',
    'isolated visual assets',
    'esy clip art workflow',
  ],
  openGraph: {
    title: 'Clip Art | Esy',
    description:
      'Isolated visual assets — generated, post-processed, and stored as durable Esy artifacts.',
    url: 'https://esy.com/clip-art/',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image' as const,
    title: 'Clip Art | Esy',
    description:
      'Isolated visual assets generated through the Esy workflow.',
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: 'https://esy.com/clip-art/',
  },
};

export default function ClipArtHub() {
  return (
    <Suspense fallback={<div className="clip-art-loading" />}>
      <ClipArtIndexClient />
    </Suspense>
  );
}
