'use client';

import React, { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { Check } from 'lucide-react';
import './RunChecklistCard.css';

/**
 * RunChecklistCard — compact, self-running "watch a run finish" card.
 *
 * A vertical checklist in brand navy/teal ticks off in green, and when
 * the run completes a result panel slides in beneath it: the shipped
 * flower asset, "Run complete", and the real cost. The checklist never
 * swaps out, so the card stays steady while it loops. Reusable anywhere
 * a live-feeling proof point is needed (hero, docs, landings).
 */

const RUN_STEPS = [
  'Intake parsed',
  'Prompt composed',
  'gpt-image-2 render',
  'Background removed',
  'Review passed',
];

// Real shipped asset + real ballpark cost, so the demo stays honest.
const RESULT = {
  image: 'https://images.clip.art/flower/colorful-flat-style-flowers-ouw8rl.webp',
  alt: 'Colorful flat-style flowers — clip art generated by this workflow and shipped on clip.art',
  cost: '$0.04',
};

const STEP_MS = 850; // per-step tick
const DONE_HOLD_MS = 5000; // how long the finished artifact stays up
const RESET_HOLD_MS = 700; // brief beat before the loop restarts

const RunChecklistCard: React.FC<{ className?: string }> = ({ className = '' }) => {
  // completed = number of steps checked off so far
  const [completed, setCompleted] = useState(0);
  const [done, setDone] = useState(false);
  const [started, setStarted] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);

  // Only animate once scrolled into view; reduced-motion users get the
  // finished state immediately (no ticking).
  useEffect(() => {
    if (typeof window !== 'undefined' &&
        window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
      setCompleted(RUN_STEPS.length);
      setDone(true);
      return;
    }
    const el = rootRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setStarted(true);
          observer.disconnect();
        }
      },
      { threshold: 0.4 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  // Run loop: tick steps → reveal result → hold → reset.
  useEffect(() => {
    if (!started) return;
    let timer: ReturnType<typeof setTimeout>;
    if (!done) {
      if (completed < RUN_STEPS.length) {
        timer = setTimeout(() => setCompleted((c) => c + 1), STEP_MS);
      } else {
        timer = setTimeout(() => setDone(true), 420);
      }
    } else {
      timer = setTimeout(() => {
        setDone(false);
        setTimeout(() => setCompleted(0), RESET_HOLD_MS);
      }, DONE_HOLD_MS);
    }
    return () => clearTimeout(timer);
  }, [started, done, completed]);

  return (
    <div
      ref={rootRef}
      className={`rcc-card ${done ? 'rcc-card--done' : ''} ${className}`}
      aria-hidden="true"
    >
      {/* Header — workflow identity, live pulse while running */}
      <div className="rcc-header">
        <span className={`rcc-status-dot ${done ? 'rcc-status-dot--done' : ''}`} />
        <span className="rcc-title">Generate Clip Art Asset</span>
      </div>

      {/* Vertical checklist — always visible, ticks off in green */}
      <ul className="rcc-steps">
        {RUN_STEPS.map((label, i) => {
          const state = i < completed ? 'done' : i === completed && !done ? 'active' : 'pending';
          return (
            <li key={label} className={`rcc-step rcc-step--${state}`}>
              <span className="rcc-step-icon">
                {state === 'done' ? (
                  <Check size={10} strokeWidth={3.5} />
                ) : state === 'active' ? (
                  <span className="rcc-spinner" />
                ) : null}
              </span>
              <span className="rcc-step-label">{label}</span>
            </li>
          );
        })}
      </ul>

      {/* Result panel — slides in under the checklist when the run lands */}
      <div className={`rcc-result ${done ? 'rcc-result--visible' : ''}`}>
        <div className="rcc-result-divider" />
        <div className="rcc-result-row">
          <div className="rcc-result-thumb">
            <Image
              src={RESULT.image}
              alt={RESULT.alt}
              width={128}
              height={128}
              unoptimized
            />
          </div>
          <div className="rcc-result-meta">
            <span className="rcc-result-line">Run complete</span>
            <span className="rcc-result-cost">{RESULT.cost}</span>
            <span className="rcc-result-sub">Reviewed &amp; shipped on clip.art</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default RunChecklistCard;
