'use client';

import React, { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { ArrowRight, Check, ChevronDown, RotateCcw, UserCheck } from 'lucide-react';
import './RunConsole.css';

/**
 * RunConsole — the homepage's "watch a real run" centerpiece.
 *
 * A three-zone execution console in brand navy/teal/white:
 *   intake card → live step trace (timing + cost per step) → artifact.
 * The trace ticks like a real observability view (Inngest/Temporal
 * pattern: the run demonstrates itself), and the artifact zone stays a
 * shimmering placeholder until the run lands, then reveals the shipped
 * asset with the run total. Cost-per-step is the Esy differentiator, so
 * it gets a dedicated column. Reusable on any dark band.
 */

interface TraceStep {
  label: string;
  detail: string;
  time: string;
  cost: string;
  /** Human-in-the-loop gate gets a distinct badge + icon */
  human?: boolean;
}

const TRACE: TraceStep[] = [
  { label: 'Intake parsed', detail: 'Subject, style & format validated', time: '0.4s', cost: '$0.000' },
  { label: 'Prompt composed', detail: 'Catalog style rules applied', time: '1.1s', cost: '$0.001' },
  { label: 'gpt-image-2 render', detail: '1024×1024 · 1 candidate', time: '19s', cost: '$0.034' },
  { label: 'Background removed', detail: 'fal.ai · stored in ESY R2', time: '4.8s', cost: '$0.004' },
  { label: 'Review passed', detail: 'Human-in-the-loop approval', time: '—', cost: '$0.000', human: true },
];

const RESULT = {
  image: 'https://images.clip.art/flower/colorful-flat-style-flowers-ouw8rl.webp',
  alt: 'Colorful flat-style flowers — generated by this workflow and shipped on clip.art',
  totalCost: '$0.04',
  totalTime: '25s',
};

const STEP_MS = 1050;

const RunConsole: React.FC<{ className?: string }> = ({ className = '' }) => {
  const [completed, setCompleted] = useState(0);
  const [done, setDone] = useState(false);
  const [started, setStarted] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);

  // Start once scrolled into view; reduced-motion users get the finished
  // console immediately.
  useEffect(() => {
    if (typeof window !== 'undefined' &&
        window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
      setCompleted(TRACE.length);
      setDone(true);
      return;
    }
    const el = rootRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setStarted(true);
          observer.disconnect();
        }
      },
      { threshold: 0.35 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  // Tick the trace; unlike the hero card this runs once and rests on the
  // finished state (a Replay affordance restarts it deliberately).
  useEffect(() => {
    if (!started || done) return;
    let timer: ReturnType<typeof setTimeout>;
    if (completed < TRACE.length) {
      timer = setTimeout(() => setCompleted((c) => c + 1), STEP_MS);
    } else {
      timer = setTimeout(() => setDone(true), 450);
    }
    return () => clearTimeout(timer);
  }, [started, done, completed]);

  const replay = () => {
    setDone(false);
    setCompleted(0);
    setStarted(true);
  };

  return (
    <div ref={rootRef} className={`rc-console ${done ? 'rc-console--done' : ''} ${className}`}>
      {/* Console chrome — run identity + state, replay once finished */}
      <div className="rc-chrome">
        <div className="rc-chrome-id">
          <span className={`rc-chrome-dot ${done ? 'rc-chrome-dot--done' : ''}`} />
          <span className="rc-chrome-name">Generate Clip Art Asset</span>
          <span className="rc-chrome-run">run #4,182 this week</span>
        </div>
        {done && (
          <button type="button" className="rc-replay" onClick={replay}>
            <RotateCcw size={12} />
            Replay run
          </button>
        )}
      </div>

      <div className="rc-zones">
        {/* ── Zone 1: intake — rendered as the actual little form,
            complete with inputs, a select, a toggle and the run button,
            so "you provide" reads as "you fill this in". ── */}
        <div className="rc-zone rc-zone--intake">
          <span className="rc-zone-label">You provide</span>
          <div className="rc-intake-card">
            <div className="rc-intake-field">
              <span className="rc-intake-key">Subject</span>
              <span className="rc-intake-input">Colorful flat-style flowers</span>
            </div>

            <div className="rc-intake-cols">
              <div className="rc-intake-field">
                <span className="rc-intake-key">Style</span>
                <span className="rc-intake-input rc-intake-input--select">
                  Flat
                  <ChevronDown size={13} />
                </span>
              </div>
              <div className="rc-intake-field">
                <span className="rc-intake-key">Format</span>
                <span className="rc-intake-input rc-intake-input--select">
                  1:1
                  <ChevronDown size={13} />
                </span>
              </div>
            </div>

            <div className="rc-intake-toggle-row">
              <span className="rc-intake-toggle" aria-hidden="true">
                <span className="rc-intake-toggle-knob" />
              </span>
              <span className="rc-intake-toggle-label">Remove background</span>
            </div>

            <span className="rc-intake-submit">
              Run workflow
              <ArrowRight size={13} />
            </span>
          </div>
          <p className="rc-zone-hint">A short form. No prompt-wrangling.</p>
        </div>

        {/* ── Zone 2: the live trace — steps, timing, cost ── */}
        <div className="rc-zone rc-zone--trace">
          <span className="rc-zone-label">Esy runs the workflow</span>
          <ol className="rc-trace">
            {TRACE.map((step, i) => {
              const state = i < completed ? 'done' : i === completed && !done ? 'active' : 'pending';
              return (
                <li key={step.label} className={`rc-step rc-step--${state}`}>
                  {/* Vertical connector fills as the run advances */}
                  {i < TRACE.length - 1 && <span className="rc-step-line" aria-hidden="true" />}
                  <span className="rc-step-icon">
                    {state === 'done' ? (
                      step.human ? <UserCheck size={11} strokeWidth={2.75} /> : <Check size={11} strokeWidth={3.5} />
                    ) : state === 'active' ? (
                      <span className="rc-spinner" />
                    ) : null}
                  </span>
                  <span className="rc-step-main">
                    <span className="rc-step-label">
                      {step.label}
                      {step.human && <span className="rc-step-badge">Human gate</span>}
                    </span>
                    <span className="rc-step-detail">{step.detail}</span>
                  </span>
                  <span className="rc-step-figures">
                    <span className="rc-step-time">{step.time}</span>
                    <span className="rc-step-cost">{step.cost}</span>
                  </span>
                </li>
              );
            })}
          </ol>
        </div>

        {/* ── Zone 3: the artifact — placeholder until the run lands ── */}
        <div className="rc-zone rc-zone--artifact">
          <span className="rc-zone-label">You get</span>
          <div className={`rc-artifact ${done ? 'rc-artifact--done' : ''}`}>
            <div className="rc-artifact-plate">
              {done ? (
                <Image
                  src={RESULT.image}
                  alt={RESULT.alt}
                  width={220}
                  height={220}
                  unoptimized
                />
              ) : (
                <div className="rc-artifact-shimmer" aria-hidden="true" />
              )}
            </div>
            <div className="rc-artifact-meta">
              {done ? (
                <>
                  <span className="rc-artifact-status">
                    <Check size={12} strokeWidth={3.5} /> Run complete
                  </span>
                  <span className="rc-artifact-total">
                    {RESULT.totalCost}
                    <span className="rc-artifact-total-sub"> · {RESULT.totalTime}</span>
                  </span>
                  <span className="rc-artifact-sub">Reviewed &amp; shipped on clip.art</span>
                </>
              ) : (
                <span className="rc-artifact-waiting">Rendering&hellip;</span>
              )}
            </div>
          </div>
          <p className="rc-zone-hint">
            Every run keeps its full record — prompt, model, processing &amp; cost.
          </p>
        </div>
      </div>
    </div>
  );
};

export default RunConsole;
